development:
  sessions:
    default:
      database: <%= app_name %>_development
      hosts:
        - localhost:27017
      options:
        identity_map_enabled: true
  options:
test:
  sessions:
    default:
      database: <%= app_name %>_test<%= ENV['TEST_ENV_NUMBER'] %>
      hosts:
        - "<%= ENV['MONGODB_PORT_27017_TCP_ADDR'] || 'localhost' %>:<%= ENV['MONGODB_PORT_27017_TCP_PORT'] || '27017' %>"
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: <%= app_name %>_production
      hosts:
        - localhost:27017
      options:
  options:
